name = "EarthModels"
uuid = "aaeb1028-ebc9-11e8-11f3-65db3368bf88"
authors = ["Andy Nowacki <andy.nowacki@bristol.ac.uk>"]
version = "0.2.0"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
